# Generated by Django 5.1.3 on 2024-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=100, verbose_name='Shortened URL Alias')),
                ('original_url', models.CharField(max_length=100, verbose_name='Long URL')),
                ('custom_alias', models.CharField(max_length=100, verbose_name='User Suggested Alias')),
                ('ttl_seconds', models.IntegerField(default=120)),
                ('expiry_time', models.DateTimeField(blank=True, null=True, verbose_name='Expiry time in seconds')),
                ('visits_frequency', models.IntegerField(default=0, verbose_name='Count of user visits on this URL')),
                ('last_accessed', models.JSONField(blank=True, default=[])),
            ],
        ),
    ]
