# Generated by Django 5.1.3 on 2024-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='last_accessed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='original_url',
            field=models.CharField(max_length=100, unique=True, verbose_name='Long URL'),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(max_length=100, unique=True, verbose_name='Shortened URL Alias'),
        ),
    ]
