# Generated by Django 5.1.3 on 2024-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0002_alter_urlshortener_last_accessed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='custom_alias',
            field=models.CharField(max_length=100, null=True, verbose_name='User Suggested Alias'),
        ),
    ]
