# Generated by Django 5.1.3 on 2024-11-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0004_alter_urlshortener_ttl_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='alias',
            field=models.CharField(max_length=100, null=True, verbose_name='Alias'),
        ),
    ]
